### ISSUE TITLE
Please don't require ruby 2.0

### ISSUE THREAD

**Issue by cflipse** [bsm/poseidon_cluster#12]
Can I ask why the ruby version bump?  I don't see anything in the syntax changes that would require this, and it's going to cause upgrade issues for at least one large application I work with that hasn't made move to 2.0.  (yes, I know it's end-of-lifed, but the realities of keeping an old, large monorail running mean version upgrades are approached slowly and cautiously)

Since this release is needed to be able to update against the current pre-release of poseidon, which fixes some serious delivery issues, it would be good if other changes didn't prevent upgrading.

**Comment by dim** [comment]
Sorry, could you please submit a PR?
