### ISSUE TITLE
0.3.0 broken on JRuby

### ISSUE THREAD

**Issue by tarcieri** [bsm/poseidon_cluster#17]
This commit hard locked to Ruby > 2.0.0:

https://github.com/bsm/poseidon_cluster/commit/5d77676fa5df0a469b96e5fe9d3130c48ea8f907

Specifically:

```ruby
s.required_ruby_version = '>= 2.0.0'
```

This doesn't work with JRuby 1.7.x, which still provides 1.9.3-like behavior and whose 2.0 mode is broken. It will be fixed by JRuby 9000, but that's not released yet.

AFAICT this gem doesn't actually use any Ruby 2.x specific features and it was working on JRuby when I just pulled the git repo in from GitHub. However trying to use the released gem doesn't work due to this issue.

**Comment by nicksieger** [comment]
Funny you should report this just now. #12 was closed earlier today. I'll prepare a PR.

**Comment by dim** [comment]
Fixed in #84cb966

**Comment by tarcieri** [comment]
Thanks! Just confirmed it's working on 0.3.2
