### ISSUE TITLE
Consumer group constructor does not support zookeeper connection chroot/namespace

### ISSUE THREAD

**Issue by piavlo** [bsm/poseidon_cluster#18]
Currently consumer group constructor expects an array of zookeeper servers and concatenates them into comma delimited connection string  format  and it's not possible to have namespace/chroot
like `zoo1:2181,zoo2:2181,zoo3:2181/kafka` without adding extra parameter to options
https://github.com/bsm/poseidon_cluster/blob/master/lib/poseidon/consumer_group.rb#L97
The question is why zookeeper servers are passed as array and not as connection string in the first place?
I can understand the reason for brokers as they passed asis to Poseidon::BrokerPool.new
but for zookeeper that does not make sense to pass them as array.

**Comment by dim** [comment]
Hey, could you please send a PR? Thanks

**Comment by piavlo** [comment]
@dim any chance to look at PR ? tnx

**Comment by dim** [comment]
@piavlo I don't think ensemble strings are common in Ruby, you can still pass the chroot path in the array.

**Comment by piavlo** [comment]
@dim so you are saying that ["zk1:port1", "zk2:port2","/chrrot"]  is better than native zk connection string as "zk1:port1,zk2:port2/chrrot" ?
The passing of chroot in array seems to me as a hacky workaround, which would not work anyway asis since ["zk1:port1","zk2:port2","/chroot"].join(",")  => "zk1:port1,zk2:port2,/chroot"
I don't think the extra comma before chroot is valid zk connection string.
How about supporting both array and zk connection string? This way no backwards compatibility would be broken.

**Comment by dim** [comment]
No, that's not what I meant. You can pass `["zk1:port1", "zk2:port2/chrrot"]` to achieve exactly what you are looking for

**Comment by piavlo** [comment]
Well this is a workaround ,not a clean solution, and requires to do ugly workarounds then generating config files.
Will you accept a PR which will support both array and string for zookeepers param of the constructor
in case of array it will do a join(",")
in case of string it will pass it as is
?
