### ISSUE TITLE
`sleep': execution expired (Timeout::Error) while the consumer group trying to rebalance 

### ISSUE THREAD

**Issue by iqbal-reducedata** [bsm/poseidon_cluster#9]
/Users/barak/.rvm/gems/ruby-2.1.3/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:405:in `sleep': execution expired (Timeout::Error)
	from /Users/barak/.rvm/gems/ruby-2.1.3/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:405:in `block in claim!'
	from /Users/barak/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
	from /Users/barak/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
	from /Users/barak/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:35:in `catch'
	from /Users/barak/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:35:in `catch'
	from /Users/barak/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
	from /Users/barak/.rvm/gems/ruby-2.1.3/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:402:in `claim!'
	from /Users/barak/.rvm/gems/ruby-2.1.3/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:384:in `block (2 levels) in rebalance!'
	from /Users/barak/.rvm/gems/ruby-2.1.3/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:378:in `each'
	from /Users/barak/.rvm/gems/ruby-2.1.3/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:378:in `block in rebalance!'
	from /Users/barak/.rvm/gems/ruby-2.1.3/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:368:in `synchronize'
	from /Users/barak/.rvm/gems/ruby-2.1.3/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:368:in `rebalance!'
	from /Users/barak/.rvm/gems/ruby-2.1.3/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:150:in `register!'
	from /Users/barak/.rvm/gems/ruby-2.1.3/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:106:in `initialize'
	from kafka_consumer.rb:236:in `new'
	from kafka_consumer.rb:236:in `launch_consumer'
	from kafka_consumer.rb:294:in `<main>'

**Comment by heavydawson** [comment]
Yes, we see it semi-regularly.

**Comment by dim** [comment]
Can you please try it with the latest version of poseidon and poseidon cluster?
